Explicitly tell snakemake to use all cores for local executor
Solves failure moving from snakemake 9.1.16 to 9.2.0:

ERROR    snakemake.logging:exceptions.py:181 Error: cores have to be specified for local execution (use --cores N with N being a number >= 1 or 'all')