Drop redundant explicit removal of anaconda default channel
This was giving an error on recent CI runs:

CondaKeyError: 'channels': value 'defaults' not present in config